micronaut:
  application:
    name: keyManagerRestApi
  server:
    port: ${SERVER_PORT:8081}

grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    KeyManager:
      address: '${KEY_MANAGER_HOST:localhost}:${KEY_MANAGER_PORT:50051}'
